"""empty message

Revision ID: 371357490c4a
Revises: afc7942d73fa
Create Date: 2018-05-02 23:27:28.614877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371357490c4a'
down_revision = 'afc7942d73fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'follows_follower_id_key', 'follows', type_='unique')
    op.drop_constraint(u'follows_user_id_key', 'follows', type_='unique')
    op.drop_constraint(u'likes_post_id_key', 'likes', type_='unique')
    op.drop_constraint(u'likes_user_id_key', 'likes', type_='unique')
    op.drop_constraint(u'posts_user_id_key', 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'posts_user_id_key', 'posts', ['user_id'])
    op.create_unique_constraint(u'likes_user_id_key', 'likes', ['user_id'])
    op.create_unique_constraint(u'likes_post_id_key', 'likes', ['post_id'])
    op.create_unique_constraint(u'follows_user_id_key', 'follows', ['user_id'])
    op.create_unique_constraint(u'follows_follower_id_key', 'follows', ['follower_id'])
    # ### end Alembic commands ###
