"""empty message

Revision ID: afc7942d73fa
Revises: 245ec2133e05
Create Date: 2018-04-30 03:59:21.101404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc7942d73fa'
down_revision = '245ec2133e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('postimage', sa.String(length=255), nullable=True))
    op.drop_column('posts', 'photo')
    op.add_column('users', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('image', sa.String(length=80), nullable=True))
    op.drop_column('users', 'bio')
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'image')
    op.drop_column('users', 'biography')
    op.add_column('posts', sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'postimage')
    # ### end Alembic commands ###
